version: '3.8'
services:
  nats-server:
    image: nats:latest
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
# Names our volume
volumes:
  nats-server:
# Nework naming
networks:
  nats: {}